name: CI (scaffold)

on:
  pull_request:
    branches: [ main, master ]

jobs:
  scaffold:
    if: github.repository == 'geminimir/stripemeter'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Environment info
        run: |
          echo "CI scaffold running at 2025-08-22T11:07:43.790283+00:00"
          which node && node -v || true
          which python3 && python3 --version || true
          echo "Ready to wire real build/tests once maintainers confirm commands."
